"""tab

Revision ID: d217cc37bad7
Revises: 5a9142191f90
Create Date: 2019-07-09 12:23:52.392971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd217cc37bad7'
down_revision = '5a9142191f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_description'), 'entries', ['description'], unique=False)
    op.create_index(op.f('ix_entries_title'), 'entries', ['title'], unique=False)
    op.drop_index('ix_entry_description', table_name='entry')
    op.drop_index('ix_entry_title', table_name='entry')
    op.drop_table('entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.VARCHAR(length=120), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('status IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entry_title', 'entry', ['title'], unique=False)
    op.create_index('ix_entry_description', 'entry', ['description'], unique=False)
    op.drop_index(op.f('ix_entries_title'), table_name='entries')
    op.drop_index(op.f('ix_entries_description'), table_name='entries')
    op.drop_table('entries')
    # ### end Alembic commands ###
